// Generated by https://quicktype.io

export interface PokeResponse {
  count: number;
  next: string;
  previous: null;
  results: SmallResult[];
}

export interface SmallResult {
  name: string;
  url: string;
}
